package io.agilehandy.demoreadmsword.model;

public enum PartLabels {

    NONE, TITLE, SECTION, SUB_SECTION, SUB_SECTION_DESCRIPTION, SUB_SUB_SECTION
        , SUB_SUB_SECTION_DESCRIPTION
        , QUESTION, QUESTION_CONT, ANSWER, ANSWER_CONT, NOT_VALID;
}
